### ISSUE TITLE
Please add validation

### ISSUE THREAD

**Issue by doronuziel71** [kobyost/Web-App-with-Spring-Mvc-Hibernate#1]
Hi Koby,
Please add validation to the Customer Form by doing the following:
Create a CustomerValidator interface and a DefaultCustomerValidator.
This validator should have a single method accepting Customer as an argument and returning a hash map of errors. 
Please use this validator in your controller and have the customer saved only if no errors are returned. If, on the otherhand, there are errors - please have them displayed near the corresponding fields in the form.

Doron

**Comment by kobyost** [comment]
Hi Doron,
I Added validation to the Customer Form and added bootstrap also.
There is another and more simple  way  to do validation and its by using Hibernate Validation or Spring Validation.
